; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;
; This test is based on trampoline.ll, modified for llvm.init.heap.trampoline.
; This test assumes some function malloc_exec exists which can allocate
; executable heap memory.
;
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-LINUX
; RUN: llc -mtriple=aarch64-none-eabi < %s | FileCheck %s --check-prefixes=CHECK-LINUX
; RUN: llc -mtriple=aarch64-pc-windows-msvc < %s | FileCheck %s --check-prefix=CHECK-PC
; RUN: llc -mtriple=aarch64-apple-darwin < %s | FileCheck %s --check-prefixes=CHECK-APPLE

declare ptr @malloc_exec(i64 %0)
declare void @llvm.init.heap.trampoline(ptr, ptr, ptr);
declare ptr @llvm.adjust.trampoline(ptr);

define ptr @f(ptr nest %x, i64 %y) {
; CHECK-LINUX-LABEL: f:
; CHECK-LINUX:       // %bb.0:
; CHECK-LINUX-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-LINUX-NEXT:    sub sp, sp, #237, lsl #12 // =970752
; CHECK-LINUX-NEXT:    sub sp, sp, #3264
; CHECK-LINUX-NEXT:    .cfi_def_cfa_offset 974032
; CHECK-LINUX-NEXT:    .cfi_offset w29, -16
; CHECK-LINUX-NEXT:    add x0, x15, x0
; CHECK-LINUX-NEXT:    add sp, sp, #237, lsl #12 // =970752
; CHECK-LINUX-NEXT:    add sp, sp, #3264
; CHECK-LINUX-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-LINUX-NEXT:    ret
;
; CHECK-PC-LABEL: f:
; CHECK-PC:       .seh_proc f
; CHECK-PC-NEXT:  // %bb.0:
; CHECK-PC-NEXT:    stp x29, x30, [sp, #-16]! // 16-byte Folded Spill
; CHECK-PC-NEXT:    .seh_save_fplr_x 16
; CHECK-PC-NEXT:    mov x9, x15
; CHECK-PC-NEXT:    mov x15, #60876 // =0xedcc
; CHECK-PC-NEXT:    .seh_nop
; CHECK-PC-NEXT:    bl __chkstk
; CHECK-PC-NEXT:    .seh_nop
; CHECK-PC-NEXT:    sub sp, sp, x15, lsl #4
; CHECK-PC-NEXT:    .seh_stackalloc 974016
; CHECK-PC-NEXT:    mov x15, x9
; CHECK-PC-NEXT:    .seh_endprologue
; CHECK-PC-NEXT:    add x0, x15, x0
; CHECK-PC-NEXT:    .seh_startepilogue
; CHECK-PC-NEXT:    add sp, sp, #237, lsl #12 // =970752
; CHECK-PC-NEXT:    .seh_stackalloc 970752
; CHECK-PC-NEXT:    add sp, sp, #3264
; CHECK-PC-NEXT:    .seh_stackalloc 3264
; CHECK-PC-NEXT:    ldp x29, x30, [sp], #16 // 16-byte Folded Reload
; CHECK-PC-NEXT:    .seh_save_fplr_x 16
; CHECK-PC-NEXT:    .seh_endepilogue
; CHECK-PC-NEXT:    ret
; CHECK-PC-NEXT:    .seh_endfunclet
; CHECK-PC-NEXT:    .seh_endproc
;
; CHECK-APPLE-LABEL: f:
; CHECK-APPLE:       ; %bb.0:
; CHECK-APPLE-NEXT:    stp x28, x27, [sp, #-16]! ; 16-byte Folded Spill
; CHECK-APPLE-NEXT:    sub sp, sp, #237, lsl #12 ; =970752
; CHECK-APPLE-NEXT:    sub sp, sp, #3264
; CHECK-APPLE-NEXT:    .cfi_def_cfa_offset 974032
; CHECK-APPLE-NEXT:    .cfi_offset w27, -8
; CHECK-APPLE-NEXT:    .cfi_offset w28, -16
; CHECK-APPLE-NEXT:    add x0, x15, x0
; CHECK-APPLE-NEXT:    add sp, sp, #237, lsl #12 ; =970752
; CHECK-APPLE-NEXT:    add sp, sp, #3264
; CHECK-APPLE-NEXT:    ldp x28, x27, [sp], #16 ; 16-byte Folded Reload
; CHECK-APPLE-NEXT:    ret
  %chkstack = alloca [u0xedcba x i8]
  %sum = getelementptr i8, ptr %x, i64 %y
  ret ptr %sum
}

define i64 @func1() {
; CHECK-LINUX-LABEL: func1:
; CHECK-LINUX:       // %bb.0:
; CHECK-LINUX-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-LINUX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-LINUX-NEXT:    .cfi_offset w30, -16
; CHECK-LINUX-NEXT:    mov w0, #64 // =0x40
; CHECK-LINUX-NEXT:    bl malloc_exec
; CHECK-LINUX-NEXT:    mov x9, #177 // =0xb1
; CHECK-LINUX-NEXT:    mov w8, #143 // =0x8f
; CHECK-LINUX-NEXT:    add x10, sp, #8
; CHECK-LINUX-NEXT:    movk x9, #22528, lsl #16
; CHECK-LINUX-NEXT:    movk w8, #22528, lsl #16
; CHECK-LINUX-NEXT:    add x1, x0, #12
; CHECK-LINUX-NEXT:    movk x9, #544, lsl #32
; CHECK-LINUX-NEXT:    str w8, [x0]
; CHECK-LINUX-NEXT:    adrp x8, :got:f
; CHECK-LINUX-NEXT:    movk x9, #54815, lsl #48
; CHECK-LINUX-NEXT:    stur x9, [x0, #4]
; CHECK-LINUX-NEXT:    ldr x8, [x8, :got_lo12:f]
; CHECK-LINUX-NEXT:    stp x10, x8, [x0, #16]
; CHECK-LINUX-NEXT:    bl __clear_cache
; CHECK-LINUX-NEXT:    mov x0, xzr
; CHECK-LINUX-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-LINUX-NEXT:    ret
;
; CHECK-PC-LABEL: func1:
; CHECK-PC:       .seh_proc func1
; CHECK-PC-NEXT:  // %bb.0:
; CHECK-PC-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-PC-NEXT:    .seh_save_reg_x x30, 16
; CHECK-PC-NEXT:    .seh_endprologue
; CHECK-PC-NEXT:    mov w0, #64 // =0x40
; CHECK-PC-NEXT:    bl malloc_exec
; CHECK-PC-NEXT:    mov x9, #177 // =0xb1
; CHECK-PC-NEXT:    mov w8, #143 // =0x8f
; CHECK-PC-NEXT:    add x1, x0, #12
; CHECK-PC-NEXT:    movk x9, #22528, lsl #16
; CHECK-PC-NEXT:    movk w8, #22528, lsl #16
; CHECK-PC-NEXT:    movk x9, #544, lsl #32
; CHECK-PC-NEXT:    str w8, [x0]
; CHECK-PC-NEXT:    add x8, sp, #8
; CHECK-PC-NEXT:    movk x9, #54815, lsl #48
; CHECK-PC-NEXT:    stur x9, [x0, #4]
; CHECK-PC-NEXT:    adrp x9, f
; CHECK-PC-NEXT:    add x9, x9, :lo12:f
; CHECK-PC-NEXT:    stp x8, x9, [x0, #16]
; CHECK-PC-NEXT:    bl __clear_cache
; CHECK-PC-NEXT:    mov x0, xzr
; CHECK-PC-NEXT:    .seh_startepilogue
; CHECK-PC-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-PC-NEXT:    .seh_save_reg_x x30, 16
; CHECK-PC-NEXT:    .seh_endepilogue
; CHECK-PC-NEXT:    ret
; CHECK-PC-NEXT:    .seh_endfunclet
; CHECK-PC-NEXT:    .seh_endproc
;
; CHECK-APPLE-LABEL: func1:
; CHECK-APPLE:       ; %bb.0:
; CHECK-APPLE-NEXT:    sub sp, sp, #32
; CHECK-APPLE-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-APPLE-NEXT:    .cfi_def_cfa_offset 32
; CHECK-APPLE-NEXT:    .cfi_offset w30, -8
; CHECK-APPLE-NEXT:    .cfi_offset w29, -16
; CHECK-APPLE-NEXT:    mov w0, #64 ; =0x40
; CHECK-APPLE-NEXT:    bl _malloc_exec
; CHECK-APPLE-NEXT:    mov x9, #177 ; =0xb1
; CHECK-APPLE-NEXT:    mov w8, #143 ; =0x8f
; CHECK-APPLE-NEXT:    add x1, x0, #12
; CHECK-APPLE-NEXT:    movk x9, #22528, lsl #16
; CHECK-APPLE-NEXT:    movk w8, #22528, lsl #16
; CHECK-APPLE-NEXT:    movk x9, #544, lsl #32
; CHECK-APPLE-NEXT:    str w8, [x0]
; CHECK-APPLE-NEXT:    add x8, sp, #8
; CHECK-APPLE-NEXT:    movk x9, #54815, lsl #48
; CHECK-APPLE-NEXT:    stur x9, [x0, #4]
; CHECK-APPLE-NEXT:  Lloh0:
; CHECK-APPLE-NEXT:    adrp x9, _f@PAGE
; CHECK-APPLE-NEXT:  Lloh1:
; CHECK-APPLE-NEXT:    add x9, x9, _f@PAGEOFF
; CHECK-APPLE-NEXT:    stp x8, x9, [x0, #16]
; CHECK-APPLE-NEXT:    bl ___clear_cache
; CHECK-APPLE-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-APPLE-NEXT:    mov x0, xzr
; CHECK-APPLE-NEXT:    add sp, sp, #32
; CHECK-APPLE-NEXT:    ret
; CHECK-APPLE-NEXT:    .loh AdrpAdd Lloh0, Lloh1
  %val = alloca i64
  %tramp = call ptr @malloc_exec(i64 64)
  call void @llvm.init.heap.trampoline(ptr %tramp, ptr @f, ptr %val)
  %fp = call ptr @llvm.adjust.trampoline(ptr %tramp)
  ret i64 0
}

; Check for the explicitly emitted .note.GNU-stack section (ELF only) in the
; presence of trampolines. Check that it does NOT have the executable bit set.
; UTC_ARGS: --disable
; CHECK-LINUX:         .section        ".note.GNU-stack","",@progbits
; UTC_ARGS: --enable
