; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;
; This test is based on AArch64/trampoline.ll, modified for X86 and
; llvm.init.heap.trampoline. This test assumes some function malloc_exec
; exists which can allocate executable heap memory.
;
; RUN: llc -mtriple=x86_64-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-LINUX
; RUN: llc -mtriple=x86_64-none-eabi < %s | FileCheck %s --check-prefixes=CHECK-LINUX
; RUN: llc -mtriple=x86_64-pc-windows-msvc < %s | FileCheck %s --check-prefix=CHECK-PC

declare ptr @malloc_exec(i64 %0)
declare void @llvm.init.heap.trampoline(ptr, ptr, ptr);
declare ptr @llvm.adjust.trampoline(ptr);

define ptr @f(ptr nest %x, i64 %y) {
; CHECK-LINUX-LABEL: f:
; CHECK-LINUX:       # %bb.0:
; CHECK-LINUX-NEXT:    subq $973882, %rsp # imm = 0xEDC3A
; CHECK-LINUX-NEXT:    .cfi_def_cfa_offset 973890
; CHECK-LINUX-NEXT:    leaq (%r10,%rdi), %rax
; CHECK-LINUX-NEXT:    addq $973882, %rsp # imm = 0xEDC3A
; CHECK-LINUX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-LINUX-NEXT:    retq
;
; CHECK-PC-LABEL: f:
; CHECK-PC:       # %bb.0:
; CHECK-PC-NEXT:    movl $974016, %eax # imm = 0xEDCC0
; CHECK-PC-NEXT:    callq __chkstk
; CHECK-PC-NEXT:    subq %rax, %rsp
; CHECK-PC-NEXT:    .seh_stackalloc 974016
; CHECK-PC-NEXT:    .seh_endprologue
; CHECK-PC-NEXT:    leaq (%r10,%rcx), %rax
; CHECK-PC-NEXT:    .seh_startepilogue
; CHECK-PC-NEXT:    addq $974016, %rsp # imm = 0xEDCC0
; CHECK-PC-NEXT:    .seh_endepilogue
; CHECK-PC-NEXT:    retq
; CHECK-PC-NEXT:    .seh_endproc
  %chkstack = alloca [u0xedcba x i8]
  %sum = getelementptr i8, ptr %x, i64 %y
  ret ptr %sum
}

define i64 @func1() {
; CHECK-LINUX-LABEL: func1:
; CHECK-LINUX:       # %bb.0:
; CHECK-LINUX-NEXT:    pushq %rax
; CHECK-LINUX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-LINUX-NEXT:    movl $64, %edi
; CHECK-LINUX-NEXT:    callq malloc_exec@PLT
; CHECK-LINUX-NEXT:    movq f@GOTPCREL(%rip), %rcx
; CHECK-LINUX-NEXT:    movq %rcx, 2(%rax)
; CHECK-LINUX-NEXT:    movq %rsp, %rcx
; CHECK-LINUX-NEXT:    movq %rcx, 12(%rax)
; CHECK-LINUX-NEXT:    movw $-17591, (%rax) # imm = 0xBB49
; CHECK-LINUX-NEXT:    movw $-17847, 10(%rax) # imm = 0xBA49
; CHECK-LINUX-NEXT:    movw $-183, 20(%rax)
; CHECK-LINUX-NEXT:    movb $-29, 22(%rax)
; CHECK-LINUX-NEXT:    xorl %eax, %eax
; CHECK-LINUX-NEXT:    popq %rcx
; CHECK-LINUX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-LINUX-NEXT:    retq
;
; CHECK-PC-LABEL: func1:
; CHECK-PC:       # %bb.0:
; CHECK-PC-NEXT:    subq $40, %rsp
; CHECK-PC-NEXT:    .seh_stackalloc 40
; CHECK-PC-NEXT:    .seh_endprologue
; CHECK-PC-NEXT:    movl $64, %ecx
; CHECK-PC-NEXT:    callq malloc_exec
; CHECK-PC-NEXT:    leaq f(%rip), %rcx
; CHECK-PC-NEXT:    movq %rcx, 2(%rax)
; CHECK-PC-NEXT:    leaq {{[0-9]+}}(%rsp), %rcx
; CHECK-PC-NEXT:    movq %rcx, 12(%rax)
; CHECK-PC-NEXT:    movw $-17591, (%rax) # imm = 0xBB49
; CHECK-PC-NEXT:    movw $-17847, 10(%rax) # imm = 0xBA49
; CHECK-PC-NEXT:    movw $-183, 20(%rax)
; CHECK-PC-NEXT:    movb $-29, 22(%rax)
; CHECK-PC-NEXT:    xorl %eax, %eax
; CHECK-PC-NEXT:    .seh_startepilogue
; CHECK-PC-NEXT:    addq $40, %rsp
; CHECK-PC-NEXT:    .seh_endepilogue
; CHECK-PC-NEXT:    retq
; CHECK-PC-NEXT:    .seh_endproc
  %val = alloca i64
  %tramp = call ptr @malloc_exec(i64 64)
  call void @llvm.init.heap.trampoline(ptr %tramp, ptr @f, ptr %val)
  %fp = call ptr @llvm.adjust.trampoline(ptr %tramp)
  ret i64 0
}

; Check for the explicitly emitted .note.GNU-stack section (ELF only) in the
; presence of trampolines. Check that it does NOT have the executable bit set.
; UTC_ARGS: --disable
; CHECK-LINUX:         .section        ".note.GNU-stack","",@progbits
; UTC_ARGS: --enable
